### ISSUE TITLE
NPE during World Generation

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/AlchemyPlantGenerator#9]
### How to reproduce

1. Start Terasology
2. Select "CoreGameplay" template and add "Alchemy - Plant Generator" module in Advanced Gameplay Setup
3. Observe game creation fails during world generation with a NullPointerException

### Logs

Error Stacktrace:
```
13:11:26.335 [main] ERROR o.t.engine.core.modes.StateLoading - Error while loading org.terasology.engine.core.modes.loadProcesses.InitialiseWorldGenerator@568384ba
java.lang.NullPointerException: null
	at org.terasology.AlchemyPlantRasterizer.initialize(AlchemyPlantRasterizer.java:40)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.terasology.engine.world.generation.WorldImpl.initialize(WorldImpl.java:82)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.initialize(BaseFacetedWorldGenerator.java:58)
	at org.terasology.engine.core.modes.loadProcesses.InitialiseWorldGenerator.step(InitialiseWorldGenerator.java:34)
	at org.terasology.engine.core.modes.StateLoading.update(StateLoading.java:259)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:512)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:472)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:448)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:414)
	at org.terasology.engine.Terasology.call(Terasology.java:190)
	at org.terasology.engine.Terasology.call(Terasology.java:70)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.terasology.engine.Terasology.main(Terasology.java:139)
```

Full Log: https://pastebin.com/wcatc3ix

**Comment by jdrueckert** [comment]
This issue was reported by Discord user Shoruke.

**Comment by jdrueckert** [comment]
This module is not part of our current set of focus gameplays, so it should be investigated in a time-boxed manner to avoid spending too much effort on it (yet). If it turns out to be costly to fix or not trivial to debug, we'll have to shift it back due to other priorities.
